name: self-hosted
on: [push]
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
       - name: Set up Maven
         uses: stCarolas/setup-maven@v4.3
         with:
          maven-version: 3.8.2

